In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk', 
'the glass of juice', 
'a cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'a cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words']

In [4]:
# Define the Vocabulary size
voc_size = 1000

In [5]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[554, 802, 737, 307],
 [554, 802, 737, 151],
 [387, 585, 737, 875],
 [385, 854, 387, 781, 459],
 [385, 854, 387, 781, 326],
 [100, 554, 443, 737, 888]]

In [6]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen = sent_length)  # adds 0's in front
# embedded_docs = pad_sequences(one_hot_repr, padding='post', maxlen = sent_length)  # adds 0's in last
print(embedded_docs)

[[  0   0   0   0 554 802 737 307]
 [  0   0   0   0 554 802 737 151]
 [  0   0   0   0 387 585 737 875]
 [  0   0   0 385 854 387 781 459]
 [  0   0   0 385 854 387 781 326]
 [  0   0   0 100 554 443 737 888]]


In [9]:
# feature representation 
dim = 10


In [10]:
model = Sequential()
model.add(Embedding(voc_size, output_dim=dim))
model.compile('adam', 'mse')

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step


array([[[-0.04751638, -0.0337636 , -0.01216869,  0.00862817,
          0.04964404, -0.03888205, -0.02240164, -0.04050447,
         -0.03925958,  0.027691  ],
        [-0.04751638, -0.0337636 , -0.01216869,  0.00862817,
          0.04964404, -0.03888205, -0.02240164, -0.04050447,
         -0.03925958,  0.027691  ],
        [-0.04751638, -0.0337636 , -0.01216869,  0.00862817,
          0.04964404, -0.03888205, -0.02240164, -0.04050447,
         -0.03925958,  0.027691  ],
        [-0.04751638, -0.0337636 , -0.01216869,  0.00862817,
          0.04964404, -0.03888205, -0.02240164, -0.04050447,
         -0.03925958,  0.027691  ],
        [ 0.02679   , -0.00289302,  0.01058258, -0.04568503,
          0.03014963,  0.00286385,  0.03197933, -0.0260965 ,
          0.03925734,  0.01924074],
        [ 0.0086896 , -0.03158412, -0.030784  ,  0.00701845,
         -0.03256257,  0.03751185,  0.03931472,  0.03788295,
          0.00626205, -0.00795599],
        [-0.00729225, -0.04535426,  0.0120335 ,  0.0

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (6, 8, 10)             │        10,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,000 (39.06 KB)

 Trainable params: 10,000 (39.06 KB)

 Non-trainable params: 0 (0.00 B)