In [2]:
# !conda install pandas numpy matplotlib seaborn scikit-learn jupyter notebook

# Numpy Practice 
___
### 1. Importing Numpy
Import Numpy in your applications by adding the import keyword.

NumPy is usually imported under the 'np' alias


In [3]:
import numpy as np
import pandas as pd

Checking NumPy Version

In [4]:
pd.__version__
np.__version__

'2.2.5'

___

### 2. Calling an array
1. Arrays of different Dimension 
    - 0-D Array 
        - 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
    - 1-D Array
        - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

        - These are the most common and basic arrays


    
    - 2-D Array

In [47]:
arr = np.array([ 1, 2, 3, 4, 5])
print(f"{arr} is {type(arr)} type")

[1 2 3 4 5] is <class 'numpy.ndarray'> type


In [6]:
arr0 = np.array(42)
print(f'Example of 0-D Array : {arr0}')

Example of 0-D Array : 42


In [7]:
arr1  = np.array(range(11, 34, 3))
print(f'Example of 1-D Array : {arr1}')

Example of 1-D Array : [11 14 17 20 23 26 29 32]


In [8]:
arr2 = np.array([range(1,6), range(3,8)])
print(f"Example of 2-D Array :\n{arr2}")

Example of 2-D Array :
[[1 2 3 4 5]
 [3 4 5 6 7]]


In [9]:
arr3 = np.array([[range(1, 10, 2), range(3, 12, 2), range(6, 15, 2)]])
print(f"Example of 3-D Array :\n{arr3}")

Example of 3-D Array :
[[[ 1  3  5  7  9]
  [ 3  5  7  9 11]
  [ 6  8 10 12 14]]]


2. Checking Dimension of the arrays

In [10]:
print(f'Dimension of arr0 : {arr0.ndim}')
print(f'Dimension of arr1 : {arr1.ndim}')
print(f'Dimension of arr2 : {arr2.ndim}')
print(f'Dimension of arr3 : {arr3.ndim}')

Dimension of arr0 : 0
Dimension of arr1 : 1
Dimension of arr2 : 2
Dimension of arr3 : 3


3. Using 'ndimn' (ndmin and ndim are different)

In [11]:
arr4  = np.array([1,2,3, 4], ndmin=5)
print(arr)
print(f'Dimension of arr4 : {arr4.ndim}')

[1 2 3 4 5]
Dimension of arr4 : 5


___
## 3. Acessing Array
- Acessing 1-D Array


In [ ]:
ar1 = np.array([1, 2, 3, 4])
print(ar1[2]) #3rd element


3
10
3
[7 8 9]


- Acessing 2-D Array

In [ ]:
ar2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(ar2[1,-1])   # Last element of 2nd array

10



- Acessing 3-D Array

In [39]:
ar3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# 3rd element of 2nd array of 1st
print(ar3[1,0,1])  

8


___
### 4. Checking Data Type of an array (arr.dtype)

- List of all data types in numpy
    - i - integer
    - b - boolean
    - u - unsigned integer
    - f - float
    - c - complex float
    - m - timedelta
    - M - datetime
    - O - object
    - S - string
    - U - unicode string
    - V - fixed chunk of memory for other type ( void )

In [45]:
sarr = np.array([1, 2, 3, 4])

print(sarr.dtype)

int64


In [46]:
sarr = np.array(['apple', 'banana', 'cherry'])

print(sarr.dtype)

<U6


___
### 5. Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements