In [1]:
# !conda install pandas numpy matplotlib seaborn scikit-learn jupyter notebook

# NumPy Practice 
___
### 1. Importing NumPy
- Numpy stands for Numerical Python

- Import Numpy in the applications by adding the import keyword.

- NumPy is usually imported under the 'np' alias


In [2]:
import numpy as np
import pandas as pd

- Checking NumPy Version

In [3]:
pd.__version__
np.__version__

'2.2.5'

### 2. Calling an array
#### 2.1 Arrays of different Dimension 
- 0-D Array 
    - 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

- 1-D Array
    - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

    - These are the most common and basic arrays
  
- 2-D Array
    - An array that has 2-D arrays (matrices) as its elements is called 3-D array.

    - These are often used to represent a 3rd order tensor.

In [4]:
arr = np.array([ 1, 2, 3, 4, 5])
print(f"{arr} is {type(arr)} type")

[1 2 3 4 5] is <class 'numpy.ndarray'> type


In [5]:
arr0 = np.array(42)
print(f'Example of 0-D Array : {arr0}')

Example of 0-D Array : 42


In [6]:
arr1  = np.array(range(11, 34, 3))
print(f'Example of 1-D Array : {arr1}')

Example of 1-D Array : [11 14 17 20 23 26 29 32]


In [7]:
arr2 = np.array([range(1,6), range(3,8)])
print(f"Example of 2-D Array :\n{arr2}")

Example of 2-D Array :
[[1 2 3 4 5]
 [3 4 5 6 7]]


In [8]:
arr3 = np.array([[range(1, 10, 2), range(3, 12, 2), range(6, 15, 2)]])
print(f"Example of 3-D Array :\n{arr3}")

Example of 3-D Array :
[[[ 1  3  5  7  9]
  [ 3  5  7  9 11]
  [ 6  8 10 12 14]]]


#### 2.2 Checking Dimension of the arrays

In [9]:
print(f'Dimension of arr0 : {arr0.ndim}')
print(f'Dimension of arr1 : {arr1.ndim}')
print(f'Dimension of arr2 : {arr2.ndim}')
print(f'Dimension of arr3 : {arr3.ndim}')

Dimension of arr0 : 0
Dimension of arr1 : 1
Dimension of arr2 : 2
Dimension of arr3 : 3


#### 2.3 Using 'ndmin' (ndmin and ndim are different)

In [10]:
arr4  = np.array([1, 2, 3, 4], ndmin=5)
print(arr4)
print(f'Dimension of arr4 : {arr4.ndim}')

[[[[[1 2 3 4]]]]]
Dimension of arr4 : 5


### 3. Acessing Array
- Acessing 1-D Array



In [11]:
arr1 = np.array([1, 2, 3, 4])
print(arr1[2]) #3rd element


3


- Acessing 2-D Array

In [12]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2[1,-1])   # Last element of 2nd array

10



- Acessing 3-D Array

In [13]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# 3rd element of 2nd array of 1st
print(arr3[1,0,1])  

8


Slicing works same int the Arrays as they did in List.

### 4. Checking Data Type of an array (arr.dtype)

- List of all data types in numpy
    - i - integer
    - b - boolean
    - u - unsigned integer
    - f - float
    - c - complex float
    - m - timedelta
    - M - datetime
    - O - object
    - S - string
    - U - unicode string
    - V - fixed chunk of memory for other type (void )

In [14]:
sarr = np.array([1, 2, 3, 4])

print(sarr.dtype)

int64


In [15]:
sarr = np.array(['apple', 'banana', 'cherry'])

print(sarr.dtype)

<U6



### 5. Creating Arrays With a Defined Data Type

- We use the **array()** function to create arrays, this function can take an optional argument: **dtype** that allows us to define the expected data type of the array elements

In [16]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [17]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


- Converting Data Type on Existing Arrays

In [18]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [19]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


### 6. Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- Changes is **Copy** does not affect the original Array.

- But changes in **View** will also reflect in the original Array 

In [20]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42 # Won't get chaged in x

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42 # Will get chaged in x

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


#### 6.1 Check whether the Array Owns it's data
- Every NumPy array has the attribute base that returns None if the array owns the data.

- Otherwise, the base  attribute refers to the original object.

In [22]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### 7. NumPy Array Shape
The shape of an array is the number of elements in each dimension.


In [23]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [24]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### 8. NumPy Array Reshaping

- Reshaping means changing the shape of an array.

- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) # from 1-D to 2-D
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3) # from 1-D to 3-D
print(newarr.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
arr = np.array([[1, 2, 3, 4, 5, 6,], [7, 8, 9, 10, 11, 12]])

newarr = arr.reshape(-1) # from 1-D to 3-D
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### 9. NumPy Array Iterating
- Iterating means going through elements one by one.

- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

#### 9.1 Iterating 1-D Arrays

In [28]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


#### 9.2 Iterating 2-D Arrays

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6


#### 9.3 Iterating 3-D Arrays

In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
  for j in i :
    for k in j :
        print(k)

1
2
3
4
5
6
7
8
9
10
11
12


#### 9.4 Iterating Arrays Using **nditer()**

In [31]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
7
8


#### 9.5 Iterating Array With Different Data Types

In [32]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


### 10. NumPy Joining Array

- Joining means putting contents of two or more arrays in a single array.

- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

- We pass a sequence of arrays that we want to join to the **concatenate()** function, along with the axis. If axis is not explicitly passed, it is taken as 0.


In [33]:
arr1 = np.array([ 1, 2, 3, 4])
arr2 = np.array([ 5, 6, 7])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6 7]


- Join two 2-D arrays along rows (axis=1):

In [34]:
arr1 = np.array([[ 1, 2], [4, 5]])
arr2 = np.array([[ 7, 8], [ 9, 0]])

arr3 = np.concatenate((arr1, arr2), axis = 1)
print(arr3)

[[1 2 7 8]
 [4 5 9 0]]


#### 10.1 Joining Arrays Using Stack Functions

- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

- We pass a sequence of arrays that we want to join to the **stack()** method along with the axis. If axis is not explicitly passed it is taken as 0.

In [35]:
arr1 = np.array([ 1, 2, 3, ])
arr2 = np.array([ 5, 6, 7])

# arr3 = np.concatenate((arr1, arr2), axis=1)   # Returns an Error, becasuse axis = 1
arr4 = np.stack((arr1, arr2), axis=1)
print(arr3)
print(arr4)

[[1 2 7 8]
 [4 5 9 0]]
[[1 5]
 [2 6]
 [3 7]]


#### 10.1.1 Stacking Along Rows
- NumPy provides a helper function: **hstack()** to stack along rows.

In [36]:
arr1 = np.array([ 1, 2, 3, 4])
arr2 = np.array([ 5, 6 ,7])

arr3 = np.hstack((arr1, arr2))
print(arr3)

[1 2 3 4 5 6 7]


#### 10.1.2 Stacking Along Columns
- NumPy provides a helper function: **vstack()**  to stack along columns.

In [37]:
arr1 = np.array([ 1, 2, 3,])
arr2 = np.array([ 5, 6, 7])

arr3 = np.vstack((arr1, arr2))
print(arr3)

[[1 2 3]
 [5 6 7]]


#### 10.1.3 Stacking Along Height (depth)
- NumPy provides a helper function: **dstack()** to stack along height, which is the same as depth.

In [38]:
arr1 = np.array([ 1, 2, 3])
arr2 = np.array([ 4, 5, 6])

arr3 = np.dstack((arr1, arr2))
print(arr3.ndim)

3


### 11. NumPy Splitting Array

- Splitting is reverse operation of Joining.

- Joining merges multiple arrays into one and Splitting breaks one array into multiple.

- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [39]:
arr = np.array([ 1, 2, 3, 4, 5, 6, 7])
spa = np.array_split(arr, 3)
print(spa)
print(spa[0])
print(spa[1])
print(spa[2])

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[1 2 3]
[4 5]
[6 7]


#### 11.1 Splitting 2-D Arrays

- Use the same syntax when splitting 2-D arrays.

- Use the array_split() method, pass in the array we want to split and the number of splits we want to do.

In [40]:
arr = np.array([[ 1, 2, 3], [ 4, 5, 6], [7, 8, 9]])
spa = np.array_split(arr, 2)
print(spa)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [41]:
arr = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9], [ 0, 0, 0]])
spa = np.array_split(arr, 4, axis=1)
print(spa)
print(spa[0])
print(spa[1])

[array([[1],
       [4],
       [7],
       [0]]), array([[2],
       [5],
       [8],
       [0]]), array([[3],
       [6],
       [9],
       [0]]), array([], shape=(4, 0), dtype=int64)]
[[1]
 [4]
 [7]
 [0]]
[[2]
 [5]
 [8]
 [0]]


### 12. NumPy Searching Arrays

- We can search an array for a certain value, and return the indexes that get a match.

- To search an array, use the **where()** method.

In [42]:
arr = np.array([ 1, 7, 9, 3, 7, 7, 6, 7])

x = np.where(arr == 7)
print(x)

(array([1, 4, 5, 7]),)


In [43]:
arr = np.array(range(11))

# print(arr1)
x = np.where(arr%2 == 0)
print(x)

(array([ 0,  2,  4,  6,  8, 10]),)


#### 12.1 Search Sorted

- There is a method called **searchsorted()** which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

- **Must be used in an Sorted Array**

In [44]:
arr = np.array([ 0, 1, 2, 3, 3, 3, 4, 5, 5, 6 ])

x = np.searchsorted(arr, 3) # 3 should be inserted at index 3 
# this returns the left most index for the value to be insterted at
print(x)

3


#### 12.2 Search from the Right Side

- By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [45]:
arr = np.array([0, 1, 2, 3, 3, 3, 4, 5, 5, 6 ])

x = np.searchsorted(arr, 3, side = 'right')# 3 should be inserted at index 6 
# this returns the right most index for the value to be inserted at
print(x)

6


#### 12.3 Multiple Values
- To search for more than one value, use an array with the specified values.

In [46]:
arr = np.array([ 1, 3, 5, 6])

x = np.searchsorted(arr, [ 2, 4, 7])
print(x)

[1 2 4]


### 13. Sorting Array
- Sorting means putting elements in an ordered sequence.

- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

- The NumPy ndarray object has a function called **sort()**, that will sort a specified array.

In [47]:
arr = np.array([7, 12, 48, 93, 1, 17, 90, 100])

print(np.sort(arr))
#This method returns a copy of the array, leaving the original array unchanged.

[  1   7  12  17  48  90  93 100]


- We can also sort arrays of strings, or any other data type

In [48]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [49]:
arr = np.array([True, False, False])

print(np.sort(arr))

[False False  True]


#### 13.1 Sorting a 2-D Array
- If we use the **sort()** method on a 2-D array, both arrays will be sorted.

In [50]:
arr = np.array([[8,7,3], [5,3,0]])

print(np.sort(arr))
# Every Array gets individually sorted

[[3 7 8]
 [0 3 5]]


### 14. NumPy Filter Array
- Getting some elements out of an existing array and creating a new array out of them is called filtering.

- In NumPy, we filter an array using a boolean index list.
- If the value at an index is True that element is contained in the filtered array.
- If the value at that index is False that element is excluded from the filtered array.

In [51]:
arr = np.array(range(5, 20, 3))
x = [True, True, True, False, False, ]

newarr = arr[x]
print(newarr)

[ 5  8 11]


In [52]:
print(True==1)

True


- The common use is to create a filter array based on conditions.

In [53]:
arr = np.array(range(7,17))

filarr = []

for e in arr:
    if e%2 == 0 :
        filarr.append(True)
    else:
        filarr.append(False)


newarr = arr[filarr]
print(newarr)

[ 8 10 12 14 16]


- Creating Filter Directly From Array

In [54]:
arr = np.array(range(11))

filarr = arr > 5
newarr = arr[filarr]

print(filarr)
print(newarr)

[False False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
