In [2]:
# !conda install pandas numpy matplotlib seaborn scikit-learn jupyter notebook

# NumPy Practice 
___
## 1. Importing NumPy
Import Numpy in your applications by adding the import keyword.

NumPy is usually imported under the 'np' alias


In [3]:
import numpy as np
import pandas as pd

Checking NumPy Version

In [4]:
pd.__version__
np.__version__

'2.2.5'

## 2. Calling an array
### 2.1 Arrays of different Dimension 
- 0-D Array 
    - 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

- 1-D Array
    - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

    - These are the most common and basic arrays
  
- 2-D Array
    - An array that has 2-D arrays (matrices) as its elements is called 3-D array.

    - These are often used to represent a 3rd order tensor.

In [5]:
arr = np.array([ 1, 2, 3, 4, 5])
print(f"{arr} is {type(arr)} type")

[1 2 3 4 5] is <class 'numpy.ndarray'> type


In [6]:
arr0 = np.array(42)
print(f'Example of 0-D Array : {arr0}')

Example of 0-D Array : 42


In [7]:
arr1  = np.array(range(11, 34, 3))
print(f'Example of 1-D Array : {arr1}')

Example of 1-D Array : [11 14 17 20 23 26 29 32]


In [8]:
arr2 = np.array([range(1,6), range(3,8)])
print(f"Example of 2-D Array :\n{arr2}")

Example of 2-D Array :
[[1 2 3 4 5]
 [3 4 5 6 7]]


In [9]:
arr3 = np.array([[range(1, 10, 2), range(3, 12, 2), range(6, 15, 2)]])
print(f"Example of 3-D Array :\n{arr3}")

Example of 3-D Array :
[[[ 1  3  5  7  9]
  [ 3  5  7  9 11]
  [ 6  8 10 12 14]]]


### 2.2 Checking Dimension of the arrays

In [10]:
print(f'Dimension of arr0 : {arr0.ndim}')
print(f'Dimension of arr1 : {arr1.ndim}')
print(f'Dimension of arr2 : {arr2.ndim}')
print(f'Dimension of arr3 : {arr3.ndim}')

Dimension of arr0 : 0
Dimension of arr1 : 1
Dimension of arr2 : 2
Dimension of arr3 : 3


### 2.3 Using 'ndmin' (ndmin and ndim are different)

In [11]:
arr4  = np.array([1, 2, 3, 4], ndmin=5)
print(arr4)
print(f'Dimension of arr4 : {arr4.ndim}')

[[[[[1 2 3 4]]]]]
Dimension of arr4 : 5


## 3. Acessing Array
- Acessing 1-D Array



In [12]:
arr1 = np.array([1, 2, 3, 4])
print(arr1[2]) #3rd element


3


- Acessing 2-D Array

In [13]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2[1,-1])   # Last element of 2nd array

10



- Acessing 3-D Array

In [14]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# 3rd element of 2nd array of 1st
print(arr3[1,0,1])  

8


Slicing works same int the Arrays as they did in List.

## 4. Checking Data Type of an array (arr.dtype)

- List of all data types in numpy
    - i - integer
    - b - boolean
    - u - unsigned integer
    - f - float
    - c - complex float
    - m - timedelta
    - M - datetime
    - O - object
    - S - string
    - U - unicode string
    - V - fixed chunk of memory for other type ( void )

In [15]:
sarr = np.array([1, 2, 3, 4])

print(sarr.dtype)

int64


In [16]:
sarr = np.array(['apple', 'banana', 'cherry'])

print(sarr.dtype)

<U6



## 5. Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

In [17]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


Converting Data Type on Existing Arrays

In [19]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [20]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## 6. Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- Changes is **Copy** does not affect the original Array.

- But changes in **View** will also reflect in the original Array 

In [21]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42 # Won't get chaged in x

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [22]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42 # Will get chaged in x

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Check whether the Array Owns it's data
- Every NumPy array has the attribute base that returns None if the array owns the data.

- Otherwise, the base  attribute refers to the original object.

In [23]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## 7. NumPy Array Shape
The shape of an array is the number of elements in each dimension.


In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [25]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### 8. NumPy Array Reshaping

- Reshaping means changing the shape of an array.

- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) # from 1-D to 2-D
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3) # from 1-D to 3-D
print(newarr.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
arr = np.array([[1, 2, 3, 4, 5, 6,], [7, 8, 9, 10, 11, 12]])

newarr = arr.reshape(-1) # from 1-D to 3-D
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 9. NumPy Array Iterating
- Iterating means going through elements one by one.

- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

### 9.1 Iterating 1-D Arrays

In [31]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


### 9.2 Iterating 2-D Arrays

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6


### 9.3 Iterating 3-D Arrays

In [34]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
  for j in i :
    for k in j :
        print(k)

1
2
3
4
5
6
7
8
9
10
11
12


### 9.4 Iterating Arrays Using 'nditer()'

In [35]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
7
8


### 9.5 Iterating Array With Different Data Types

In [36]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
